# syntax=docker/dockerfile:1.6
# Generated by `mandu deploy --target=docker`.
# Multi-stage build: deps -> build -> runtime. Final image ships only
# the production node_modules + the `.mandu/` build output.

ARG BUN_IMAGE=oven/bun:1.3.12-alpine

# ---- base ----
FROM ${BUN_IMAGE} AS base
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# ---- deps ----
FROM base AS deps
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile --production

# ---- build ----
FROM base AS build
COPY . .
RUN bun install --frozen-lockfile
RUN bun run build

# ---- runtime ----
FROM base AS runtime
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/.mandu ./.mandu
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/app ./app

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/ || exit 1

CMD ["bun", "run", "mandu", "start"]
