/**
 * 24개 공약 — declarative seed
 * partyId / candidateId 는 앞선 seed의 고정 uuid 참조.
 */

const PARTY = {
  democratic: "11111111-1111-4000-8000-000000000001",
  ppp:        "11111111-1111-4000-8000-000000000002",
  rebuilding: "11111111-1111-4000-8000-000000000003",
  reform:     "11111111-1111-4000-8000-000000000004",
} as const;

const cid = (n: number) => `22222222-2222-4000-8000-${String(n).padStart(12, "0")}`;
const pid = (n: number) => `33333333-3333-4000-8000-${String(n).padStart(12, "0")}`;
const date = (s: string) => `${s}T00:00:00.000Z`;

export const env = ["dev", "staging"] as const;

export default {
  resource: "pledge",
  key: "id",
  env: ["dev", "staging"] as const,
  data: [
    // 서울시장 후보 공약
    { id: pid(1), partyId: PARTY.democratic, candidateId: cid(1), candidateName: "홍길동", candidatePosition: "서울시장",
      title: "기본소득 월 30만원 전 국민 지급",
      summary: "만 18세 이상 전 국민에게 월 30만원의 기본소득을 지급하여 최소한의 생활 안정을 보장합니다. 재원은 디지털세, 탄소세, 토지보유세 등 신규 세원을 통해 마련합니다.",
      category: "복지", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 214, downvotes: 42, commentCount: 89,
      author: "민주당 정책위", tags: JSON.stringify(["기본소득", "복지확대", "경제"]), createdAt: date("2025-05-10") },
    { id: pid(2), partyId: PARTY.ppp, candidateId: cid(2), candidateName: "김철수", candidatePosition: "서울시장",
      title: "법인세 인하로 기업 경쟁력 강화",
      summary: "법인세 최고세율을 22%에서 20%로 인하하여 기업 투자를 촉진하고 글로벌 경쟁력을 확보합니다.",
      category: "경제", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 55, downvotes: 23, commentCount: 34,
      author: "국힘 정책위", tags: JSON.stringify(["법인세", "기업경쟁력", "경제"]), createdAt: date("2025-05-10") },
    { id: pid(3), partyId: PARTY.rebuilding, candidateId: cid(3), candidateName: "이영희", candidatePosition: "서울시장",
      title: "검찰 수사권 완전 분리",
      summary: "검찰의 직접 수사권을 완전히 폐지하고, 공수처와 경찰로 수사 기능을 이관하여 검찰 권력을 견제합니다.",
      category: "행정", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 333, downvotes: 120, commentCount: 445,
      author: "혁신당 정책위", tags: JSON.stringify(["검찰개혁", "권력분산", "행정"]), createdAt: date("2025-05-10") },
    { id: pid(4), partyId: PARTY.reform, candidateId: cid(4), candidateName: "박지민", candidatePosition: "서울시장",
      title: "국회의원 세비 30% 삭감",
      summary: "국회의원 세비를 30% 삭감하고, 삭감분을 청년 창업 지원 기금으로 전환합니다.",
      category: "경제", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 644, downvotes: 31, commentCount: 156,
      author: "개혁 정책위", tags: JSON.stringify(["국회개혁", "세비삭감", "경제"]), createdAt: date("2025-05-10") },
    { id: pid(5), partyId: PARTY.democratic, candidateId: cid(1), candidateName: "홍길동", candidatePosition: "서울시장",
      title: "공공임대주택 100만호 공급",
      summary: "향후 5년간 공공임대주택 100만호를 공급하여 주거 안정을 실현합니다. 청년, 신혼부부, 고령자 맞춤형 주거 지원을 확대합니다.",
      category: "주거", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 478, downvotes: 65, commentCount: 203,
      author: "민주당 정책위", tags: JSON.stringify(["공공임대", "주거안정", "주거"]), createdAt: date("2025-05-09") },
    { id: pid(6), partyId: PARTY.ppp, candidateId: cid(2), candidateName: "김철수", candidatePosition: "서울시장",
      title: "서울 전역 무상교통 실현",
      summary: "서울시 대중교통을 전면 무상화하여 시민의 이동권을 보장하고 교통비 부담을 해소합니다.",
      category: "복지", region: "서울", subRegion: "강남구", positionTab: "서울시장",
      upvotes: 345, downvotes: 98, commentCount: 178,
      author: "국힘 정책위", tags: JSON.stringify(["무상교통", "대중교통", "복지"]), createdAt: date("2025-05-06") },
    // 강남구청장
    { id: pid(7), partyId: PARTY.democratic, candidateId: cid(5), candidateName: "최민수", candidatePosition: "강남구청장",
      title: "강남 GTX-C 역세권 개발",
      summary: "GTX-C 노선 강남 역세권을 중심으로 복합문화공간과 스타트업 허브를 조성합니다.",
      category: "경제", region: "서울", subRegion: "강남구", positionTab: "강남구청장",
      upvotes: 156, downvotes: 32, commentCount: 67,
      author: "민주당 정책위", tags: JSON.stringify(["GTX", "역세권", "경제"]), createdAt: date("2025-05-07") },
    { id: pid(8), partyId: PARTY.ppp, candidateId: cid(6), candidateName: "정수진", candidatePosition: "강남구청장",
      title: "강남 AI 교육 특구 지정",
      summary: "강남구를 AI 교육 특구로 지정하여 초중고 AI 교육 커리큘럼을 도입하고 AI 인재를 양성합니다.",
      category: "교육", region: "서울", subRegion: "강남구", positionTab: "강남구청장",
      upvotes: 203, downvotes: 28, commentCount: 89,
      author: "국힘 정책위", tags: JSON.stringify(["AI교육", "교육특구", "교육"]), createdAt: date("2025-05-07") },
    { id: pid(9), partyId: PARTY.rebuilding, candidateId: cid(7), candidateName: "한미영", candidatePosition: "강남구청장",
      title: "강남 공공보육 확대",
      summary: "강남구 내 국공립 어린이집을 50개소 추가 설치하고, 보육교사 처우를 개선합니다.",
      category: "복지", region: "서울", subRegion: "강남구", positionTab: "강남구청장",
      upvotes: 178, downvotes: 15, commentCount: 56,
      author: "혁신당 정책위", tags: JSON.stringify(["보육", "공공보육", "복지"]), createdAt: date("2025-05-06") },
    // 서울특별시의원(강남구)
    { id: pid(10), partyId: PARTY.democratic, candidateId: cid(8), candidateName: "오세훈", candidatePosition: "서울특별시의원(강남구)",
      title: "강남 대중교통 노선 확충",
      summary: "강남구 내 버스 노선을 재편하고 심야버스를 확대하여 대중교통 접근성을 높입니다.",
      category: "복지", region: "서울", subRegion: "강남구", positionTab: "서울특별시의원(강남구)",
      upvotes: 98, downvotes: 12, commentCount: 34,
      author: "민주당 정책위", tags: JSON.stringify(["대중교통", "버스노선", "교통"]), createdAt: date("2025-05-05") },
    // 강남구의원
    { id: pid(11), partyId: PARTY.ppp, candidateId: cid(9), candidateName: "김민정", candidatePosition: "강남구의원",
      title: "강남구 주차난 해소 대책",
      summary: "지하 공영주차장 5개소를 추가 건설하고 스마트 주차 시스템을 도입합니다.",
      category: "경제", region: "서울", subRegion: "강남구", positionTab: "강남구의원",
      upvotes: 134, downvotes: 22, commentCount: 45,
      author: "국힘 정책위", tags: JSON.stringify(["주차", "스마트시티", "교통"]), createdAt: date("2025-05-04") },
    // 경기도지사
    { id: pid(12), partyId: PARTY.democratic, candidateId: cid(10), candidateName: "이재명", candidatePosition: "경기도지사",
      title: "경기도 기본소득 확대",
      summary: "경기도 청년 기본소득을 월 25만원에서 40만원으로 확대하고, 대상 연령을 30세까지 넓힙니다.",
      category: "복지", region: "경기", subRegion: "수원시", positionTab: "경기도지사",
      upvotes: 523, downvotes: 87, commentCount: 312,
      author: "민주당 정책위", tags: JSON.stringify(["기본소득", "청년정책", "복지"]), createdAt: date("2025-05-10") },
    { id: pid(13), partyId: PARTY.ppp, candidateId: cid(11), candidateName: "김동연", candidatePosition: "경기도지사",
      title: "GTX 3개 노선 조기 완공",
      summary: "GTX-A, B, C 노선의 조기 완공을 추진하여 수도권 교통난을 해소합니다.",
      category: "경제", region: "경기", subRegion: "수원시", positionTab: "경기도지사",
      upvotes: 412, downvotes: 56, commentCount: 198,
      author: "국힘 정책위", tags: JSON.stringify(["GTX", "교통", "수도권"]), createdAt: date("2025-05-09") },
    { id: pid(14), partyId: PARTY.reform, candidateId: cid(12), candidateName: "조은희", candidatePosition: "경기도지사",
      title: "경기도 스타트업 펀드 1조원 조성",
      summary: "경기도 자체 스타트업 투자 펀드 1조원을 조성하여 혁신 기업을 육성합니다.",
      category: "경제", region: "경기", subRegion: "수원시", positionTab: "경기도지사",
      upvotes: 287, downvotes: 34, commentCount: 145,
      author: "개혁 정책위", tags: JSON.stringify(["스타트업", "투자", "경제"]), createdAt: date("2025-05-08") },
    // 수원시장
    { id: pid(15), partyId: PARTY.democratic, candidateId: cid(13), candidateName: "박상혁", candidatePosition: "수원시장",
      title: "수원 화성 유네스코 관광벨트 조성",
      summary: "수원 화성을 중심으로 관광벨트를 조성하고, 야간 조명 프로젝트와 문화축제를 확대합니다.",
      category: "문화", region: "경기", subRegion: "수원시", positionTab: "수원시장",
      upvotes: 189, downvotes: 23, commentCount: 78,
      author: "민주당 정책위", tags: JSON.stringify(["수원화성", "관광", "문화"]), createdAt: date("2025-05-07") },
    { id: pid(16), partyId: PARTY.ppp, candidateId: cid(14), candidateName: "이준석", candidatePosition: "수원시장",
      title: "수원 스마트시티 전환",
      summary: "수원시 전역에 IoT 인프라를 구축하고, AI 기반 교통·안전 관리 시스템을 도입합니다.",
      category: "경제", region: "경기", subRegion: "수원시", positionTab: "수원시장",
      upvotes: 167, downvotes: 31, commentCount: 56,
      author: "국힘 정책위", tags: JSON.stringify(["스마트시티", "IoT", "경제"]), createdAt: date("2025-05-06") },
    // 충남도지사
    { id: pid(17), partyId: PARTY.democratic, candidateId: cid(15), candidateName: "양승조", candidatePosition: "충남도지사",
      title: "충남 신재생에너지 허브 조성",
      summary: "태안·서산 해안에 대규모 해상풍력단지를 조성하고, 충남을 신재생에너지 수도로 만듭니다.",
      category: "환경", region: "충남", subRegion: "천안시", positionTab: "충남도지사",
      upvotes: 234, downvotes: 45, commentCount: 112,
      author: "민주당 정책위", tags: JSON.stringify(["신재생에너지", "해상풍력", "환경"]), createdAt: date("2025-05-10") },
    { id: pid(18), partyId: PARTY.ppp, candidateId: cid(16), candidateName: "김태흠", candidatePosition: "충남도지사",
      title: "충남 반도체 클러스터 유치",
      summary: "천안·아산 지역에 반도체 소부장 클러스터를 유치하여 5만개 일자리를 창출합니다.",
      category: "경제", region: "충남", subRegion: "천안시", positionTab: "충남도지사",
      upvotes: 312, downvotes: 28, commentCount: 167,
      author: "국힘 정책위", tags: JSON.stringify(["반도체", "클러스터", "일자리"]), createdAt: date("2025-05-09") },
    // 천안시장
    { id: pid(19), partyId: PARTY.democratic, candidateId: cid(17), candidateName: "박완주", candidatePosition: "천안시장",
      title: "천안역 복합환승센터 건설",
      summary: "천안역 일대에 KTX·SRT·버스를 연결하는 복합환승센터를 건설하여 교통 허브로 육성합니다.",
      category: "경제", region: "충남", subRegion: "천안시", positionTab: "천안시장",
      upvotes: 178, downvotes: 19, commentCount: 67,
      author: "민주당 정책위", tags: JSON.stringify(["천안역", "환승센터", "교통"]), createdAt: date("2025-05-08") },
    { id: pid(20), partyId: PARTY.ppp, candidateId: cid(18), candidateName: "이상천", candidatePosition: "천안시장",
      title: "천안 청년 주거 지원",
      summary: "천안시 청년 월세 지원을 월 20만원으로 확대하고, 청년 전용 공공임대 1000호를 공급합니다.",
      category: "주거", region: "충남", subRegion: "천안시", positionTab: "천안시장",
      upvotes: 145, downvotes: 12, commentCount: 45,
      author: "국힘 정책위", tags: JSON.stringify(["청년주거", "월세지원", "주거"]), createdAt: date("2025-05-07") },
    // 부산시장
    { id: pid(21), partyId: PARTY.democratic, candidateId: cid(19), candidateName: "김영춘", candidatePosition: "부산시장",
      title: "부산 2030 엑스포 후속 사업 추진",
      summary: "엑스포 유치 경험을 살려 북항 재개발과 국제 컨벤션 인프라를 확충합니다.",
      category: "경제", region: "부산", subRegion: "해운대구", positionTab: "부산시장",
      upvotes: 267, downvotes: 56, commentCount: 134,
      author: "민주당 정책위", tags: JSON.stringify(["엑스포", "북항", "경제"]), createdAt: date("2025-05-10") },
    { id: pid(22), partyId: PARTY.ppp, candidateId: cid(20), candidateName: "박형준", candidatePosition: "부산시장",
      title: "부산 글로벌 해양도시 전략",
      summary: "부산항을 동북아 물류 허브로 육성하고, 해양 관련 글로벌 기업 100개사를 유치합니다.",
      category: "경제", region: "부산", subRegion: "해운대구", positionTab: "부산시장",
      upvotes: 345, downvotes: 42, commentCount: 189,
      author: "국힘 정책위", tags: JSON.stringify(["해양도시", "물류허브", "경제"]), createdAt: date("2025-05-09") },
    { id: pid(23), partyId: PARTY.rebuilding, candidateId: cid(21), candidateName: "이정헌", candidatePosition: "부산시장",
      title: "부산 무상급식 전 학년 확대",
      summary: "초중고 전 학년 무상급식을 실시하고, 친환경 식재료 사용 비율을 80%로 높입니다.",
      category: "교육", region: "부산", subRegion: "해운대구", positionTab: "부산시장",
      upvotes: 198, downvotes: 34, commentCount: 78,
      author: "혁신당 정책위", tags: JSON.stringify(["무상급식", "친환경", "교육"]), createdAt: date("2025-05-08") },
    // 해운대구청장
    { id: pid(24), partyId: PARTY.democratic, candidateId: cid(22), candidateName: "강민구", candidatePosition: "해운대구청장",
      title: "해운대 해양레저 관광특구 조성",
      summary: "해운대 해변을 중심으로 해양레저 관광특구를 지정하고, 서핑·요트 인프라를 확충합니다.",
      category: "문화", region: "부산", subRegion: "해운대구", positionTab: "해운대구청장",
      upvotes: 156, downvotes: 18, commentCount: 56,
      author: "민주당 정책위", tags: JSON.stringify(["해양레저", "관광특구", "문화"]), createdAt: date("2025-05-07") },
  ],
};
