-- Generated by `mandu db plan` — edit with care
-- Version: 0001
-- Generated: 2026-05-17T16:18:44.113Z

CREATE TABLE "candidates" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "party_id" TEXT NOT NULL,
  "position" TEXT NOT NULL,
  "region" TEXT NOT NULL,
  "sub_region" TEXT NOT NULL,
  "pledge_count" REAL NOT NULL,
  "citizen_score" REAL NOT NULL
);
CREATE TABLE "comments" (
  "id" TEXT PRIMARY KEY,
  "pledge_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);
CREATE TABLE "parties" (
  "id" TEXT PRIMARY KEY,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "short_name" TEXT NOT NULL,
  "initial" TEXT NOT NULL,
  "color" TEXT NOT NULL,
  "logo_url" TEXT NOT NULL
);
CREATE TABLE "pledges" (
  "id" TEXT PRIMARY KEY,
  "party_id" TEXT NOT NULL,
  "candidate_id" TEXT NOT NULL,
  "candidate_name" TEXT NOT NULL,
  "candidate_position" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "region" TEXT NOT NULL,
  "sub_region" TEXT NOT NULL,
  "position_tab" TEXT NOT NULL,
  "upvotes" REAL NOT NULL,
  "downvotes" REAL NOT NULL,
  "comment_count" REAL NOT NULL,
  "author" TEXT NOT NULL,
  "tags" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);
CREATE TABLE "users" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL,
  "name" TEXT NOT NULL
);
CREATE TABLE "votes" (
  "id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "pledge_id" TEXT NOT NULL,
  "direction" REAL NOT NULL
);
