-- Generated by `mandu db plan` — edit with care
-- Version: 0002
-- Generated: 2026-05-20T01:30:49.246Z

CREATE TABLE "notifications" (
  "id" TEXT PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "pledge_id" TEXT,
  "comment_id" TEXT,
  "from_user_id" TEXT,
  "is_read" INTEGER,
  "created_at" TEXT
);
ALTER TABLE "comments" ADD COLUMN "parent_id" TEXT;
ALTER TABLE "votes" ADD COLUMN "created_at" TEXT;
