import { defineResource } from "@mandujs/core";

/**
 * Candidate Resource
 * Auto-generated by Mandu CLI
 */
export default defineResource({
  name: "candidate",
  fields: {
    id: { type: "uuid", required: true },
    name: { type: "string", required: true },
    partyId: { type: "uuid", required: true },
    position: { type: "string", required: true },
    region: { type: "string", required: true },
    subRegion: { type: "string", required: true },
    pledgeCount: { type: "number", required: true },
    citizenScore: { type: "number", required: true },
  },
  options: {
    description: "Candidate management API",
    tags: ["candidate"],
    endpoints: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
    // Persistence opts the resource into `mandu db plan` / `db apply`.
    // Adjust `provider` to match your DATABASE_URL.
    persistence: {
      provider: "sqlite",
      primaryKey: "id",
    },
  },
});
