import { defineResource } from "@mandujs/core";

/**
 * Party Resource
 * Auto-generated by Mandu CLI
 */
export default defineResource({
  name: "party",
  fields: {
    id: { type: "uuid", required: true },
    code: { type: "string", required: true },
    name: { type: "string", required: true },
    shortName: { type: "string", required: true },
    initial: { type: "string", required: true },
    color: { type: "string", required: true },
    logoUrl: { type: "url", required: true },
  },
  options: {
    description: "Party management API",
    tags: ["party"],
    endpoints: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
    // Persistence opts the resource into `mandu db plan` / `db apply`.
    // Adjust `provider` to match your DATABASE_URL.
    persistence: {
      provider: "sqlite",
      primaryKey: "id",
    },
  },
});
