import { defineResource } from "@mandujs/core";

/**
 * Pledge Resource
 * Auto-generated by Mandu CLI
 */
export default defineResource({
  name: "pledge",
  fields: {
    id: { type: "uuid", required: true },
    partyId: { type: "uuid", required: true },
    candidateId: { type: "uuid", required: true },
    candidateName: { type: "string", required: true },
    candidatePosition: { type: "string", required: true },
    title: { type: "string", required: true },
    summary: { type: "string", required: true },
    category: { type: "string", required: true },
    region: { type: "string", required: true },
    subRegion: { type: "string", required: true },
    positionTab: { type: "string", required: true },
    upvotes: { type: "number", required: true },
    downvotes: { type: "number", required: true },
    commentCount: { type: "number", required: true },
    author: { type: "string", required: true },
    tags: { type: "json", required: true },
    createdAt: { type: "date", required: true },
  },
  options: {
    description: "Pledge management API",
    tags: ["pledge"],
    endpoints: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
    // Persistence opts the resource into `mandu db plan` / `db apply`.
    // Adjust `provider` to match your DATABASE_URL.
    persistence: {
      provider: "sqlite",
      primaryKey: "id",
    },
  },
});
