import { defineResource } from "@mandujs/core";

/**
 * User Resource
 * Auto-generated by Mandu CLI
 */
export default defineResource({
  name: "user",
  fields: {
    id: { type: "uuid", required: true },
    email: { type: "email", required: true },
    name: { type: "string", required: true },
  },
  options: {
    description: "User management API",
    tags: ["user"],
    endpoints: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
    // Persistence opts the resource into `mandu db plan` / `db apply`.
    // Adjust `provider` to match your DATABASE_URL.
    persistence: {
      provider: "sqlite",
      primaryKey: "id",
    },
  },
});
