import { defineResource } from "@mandujs/core";

/**
 * Vote Resource
 * Auto-generated by Mandu CLI
 */
export default defineResource({
  name: "vote",
  fields: {
    id: { type: "uuid", required: true },
    userId: { type: "uuid", required: true },
    pledgeId: { type: "uuid", required: true },
    direction: { type: "number", required: true },
    createdAt: { type: "date", required: false },
  },
  options: {
    description: "Vote management API",
    tags: ["vote"],
    endpoints: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
    // Persistence opts the resource into `mandu db plan` / `db apply`.
    // Adjust `provider` to match your DATABASE_URL.
    persistence: {
      provider: "sqlite",
      primaryKey: "id",
    },
  },
});
